[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
# base =

# Primary accent color for interactive elements.
primaryColor = "F5F1F0"

# Background color for the main content area.
backgroundColor = "#c7e0e7"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor ="F1F7F9"

# Color used for almost all text.
textColor = "#2436aa"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# font = "serif"