[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
# base =

# Primary accent color for interactive elements.
primaryColor = "#824670"

# Background color for the main content area.
backgroundColor = "#F3F6F7"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor ="#E0DCDF"

# Color used for almost all text.
# textColor =

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# font =